### ISSUE TITLE
Accepting suggestion adds the text elsewhere

### ISSUE THREAD

**Issue by Christopher2K** [yaegassy/coc-astro#21]
Hey man! 

Thanks for maintaining this LSP! I'm encountering a weird situation where accepting a suggestion adds the text elsewhere in the template. Here's a short video:

https://github.com/yaegassy/coc-astro/assets/16650656/a4520226-5b76-470b-a27f-123a2c9851c4

As you can see, accepting the suggestion at line 52, also adds the text line 48.

I'm using the version 0.6.6 of the plugin and I have typescript enabled.

Thanks!

**Comment by yaegassy** [comment]
Thanks for the issue report. I think this problem is a glitch on the language server side.

- Similar problems
  - https://github.com/yaegassy/coc-astro/pull/16
  - https://github.com/withastro/language-tools/issues/664
